# Generated by Trae Work
# GuardYan Firmware - Audio Recorder (ADC)

import machine
import ubinascii
import time
from config import PIN_MIC, AUDIO_SAMPLE_RATE, AUDIO_DURATION_S, AUDIO_BUFFER_SIZE

class AudioRecorder:
    def __init__(self):
        self.adc = machine.ADC(machine.Pin(PIN_MIC))
        self.adc.atten(machine.ADC.ATTN_11DB)
        self.adc.width(machine.ADC.WIDTH_12BIT)

    def record(self, duration_s=AUDIO_DURATION_S):
        """Record audio via ADC and return base64 string"""
        samples = []
        interval_us = 1000000 // AUDIO_SAMPLE_RATE
        start = time.ticks_us()
        for _ in range(AUDIO_SAMPLE_RATE * duration_s):
            samples.append(self.adc.read())
            while time.ticks_diff(time.ticks_us(), start) < interval_us:
                pass
            start = time.ticks_us()
        # Simple delta encoding then base64
        buf = bytearray(len(samples) * 2)
        for i, s in enumerate(samples):
            buf[i*2] = s & 0xFF
            buf[i*2+1] = (s >> 8) & 0xFF
        return ubinascii.b2a_base64(buf).decode()
