# Generated by Trae Work
# GuardYan Firmware - Buzzer PWM Driver

import machine
from config import PIN_BUZZER

class Buzzer:
    def __init__(self):
        self.pwm = machine.PWM(machine.Pin(PIN_BUZZER))
        self.pwm.duty(0)
        self.mode = 'off'

    def _beep(self, freq, duration_ms):
        self.pwm.freq(freq)
        self.pwm.duty(512)
        time.sleep_ms(duration_ms)
        self.pwm.duty(0)

    def alert_fall(self):
        """Short beep x3 for fall confirmed"""
        self.mode = 'fall'
        for _ in range(3):
            self._beep(2000, 200)
            time.sleep_ms(200)
        self.mode = 'off'

    def start_sos(self):
        """Long beep loop for SOS"""
        self.mode = 'sos'

    def tick_sos(self):
        if self.mode == 'sos':
            self._beep(1500, 1000)
            time.sleep_ms(500)

    def start_med_reminder(self):
        """Rhythm beep for medication"""
        self.mode = 'med'

    def tick_med(self):
        if self.mode == 'med':
            self._beep(1800, 150)
            time.sleep_ms(150)
            self._beep(1800, 150)
            time.sleep_ms(1000)

    def stop(self):
        self.pwm.duty(0)
        self.mode = 'off'

import time
