# Generated by Trae Work
# GuardYan Firmware - Fall Detection Algorithm (5-State FSM)

import time
import math
from config import (
    THRESHOLD_FREE_FALL, THRESHOLD_IMPACT, THRESHOLD_ANGLE,
    THRESHOLD_STILL_LOW, THRESHOLD_STILL_HIGH, THRESHOLD_RECOVERY,
    DURATION_FREE_FALL, WINDOW_IMPACT, DURATION_STILL, WINDOW_RECOVERY
)
from mpu6050 import MPU6050

# States
STATE_NORMAL = 0
STATE_FREE_FALL = 1
STATE_IMPACT = 2
STATE_STILL = 3
STATE_FALL_CONFIRMED = 4

class FallDetector:
    def __init__(self):
        self.mpu = MPU6050()
        self.state = STATE_NORMAL
        self.state_start_ms = 0
        self.impact_time_ms = 0
        self.last_pitch = 0
        self.last_roll = 0

    def update(self):
        data = self.mpu.read_all()
        a_total = MPU6050.total_accel(data['ax'], data['ay'], data['az'])
        pitch, roll = MPU6050.pitch_roll(data['ax'], data['ay'], data['az'])
        now = time.ticks_ms()

        # State machine
        if self.state == STATE_NORMAL:
            if a_total < THRESHOLD_FREE_FALL:
                self.state = STATE_FREE_FALL
                self.state_start_ms = now

        elif self.state == STATE_FREE_FALL:
            elapsed = time.ticks_diff(now, self.state_start_ms)
            if elapsed > DURATION_FREE_FALL:
                if a_total > THRESHOLD_IMPACT:
                    self.state = STATE_IMPACT
                    self.impact_time_ms = now
                elif elapsed > WINDOW_IMPACT:
                    self.state = STATE_NORMAL

        elif self.state == STATE_IMPACT:
            if abs(pitch) > THRESHOLD_ANGLE or abs(roll) > THRESHOLD_ANGLE:
                self.state = STATE_STILL
                self.state_start_ms = now
            elif time.ticks_diff(now, self.impact_time_ms) > WINDOW_RECOVERY:
                if abs(pitch) < THRESHOLD_RECOVERY and abs(roll) < THRESHOLD_RECOVERY:
                    self.state = STATE_NORMAL

        elif self.state == STATE_STILL:
            if THRESHOLD_STILL_LOW < a_total < THRESHOLD_STILL_HIGH:
                elapsed = time.ticks_diff(now, self.state_start_ms)
                if elapsed > DURATION_STILL:
                    self.state = STATE_FALL_CONFIRMED
                    return True
            elif time.ticks_diff(now, self.impact_time_ms) > WINDOW_RECOVERY:
                if abs(pitch) < THRESHOLD_RECOVERY and abs(roll) < THRESHOLD_RECOVERY:
                    self.state = STATE_NORMAL

        elif self.state == STATE_FALL_CONFIRMED:
            self.state = STATE_NORMAL

        self.last_pitch = pitch
        self.last_roll = roll
        return False

    def get_state_name(self):
        names = ['NORMAL', 'FREE_FALL', 'IMPACT', 'STILL', 'FALL_CONFIRMED']
        return names[self.state]

    def reset(self):
        self.state = STATE_NORMAL
