# Generated by Trae Work
# GuardYan Firmware - LED PWM Driver

import machine
import math
import time
from config import PIN_LED

class LED:
    def __init__(self):
        self.pwm = machine.PWM(machine.Pin(PIN_LED))
        self.pwm.freq(1000)
        self.pwm.duty(0)
        self.mode = 'off'
        self._last_tick = 0

    def on(self):
        self.mode = 'on'
        self.pwm.duty(1023)

    def off(self):
        self.mode = 'off'
        self.pwm.duty(0)

    def breathe(self):
        self.mode = 'breathe'

    def tick_breathe(self):
        if self.mode == 'breathe':
            t = time.ticks_ms() % 2000
            duty = int(512 + 511 * math.sin(t / 2000.0 * 2 * math.pi))
            self.pwm.duty(max(0, min(1023, duty)))

    def fast_blink(self):
        self.mode = 'fast_blink'

    def tick_fast_blink(self):
        if self.mode == 'fast_blink':
            t = time.ticks_ms() % 200
            self.pwm.duty(1023 if t < 100 else 0)

    def slow_blink(self):
        self.mode = 'slow_blink'

    def tick_slow_blink(self):
        if self.mode == 'slow_blink':
            t = time.ticks_ms() % 1000
            self.pwm.duty(1023 if t < 500 else 0)

    def update(self):
        if self.mode == 'breathe':
            self.tick_breathe()
        elif self.mode == 'fast_blink':
            self.tick_fast_blink()
        elif self.mode == 'slow_blink':
            self.tick_slow_blink()
