# Generated by Trae Work
# GuardYan Firmware - Main Event Loop

import time
import machine
import ujson
from config import DEVICE_ID
from fall_detector import FallDetector
from sos_handler import SOSHandler
from buzzer import Buzzer
from led import LED
from audio import AudioRecorder
from mqtt_client import MQTTManager

class GuardYanDevice:
    def __init__(self):
        self.fall = FallDetector()
        self.sos = SOSHandler()
        self.buzzer = Buzzer()
        self.led = LED()
        self.audio = AudioRecorder()
        self.mqtt = MQTTManager(on_message=self._on_mqtt_cmd)
        self.sos_active = False
        self.med_active = False

    def _on_mqtt_cmd(self, topic, msg):
        try:
            cmd = ujson.loads(msg)
            action = cmd.get('action')
            if action == 'mute':
                self.buzzer.stop()
                self.led.off()
                self.sos_active = False
            elif action == 'reboot':
                machine.reset()
        except:
            pass

    def _publish(self, event_type, description, audio_b64=None):
        payload = {
            'type': event_type,
            'device_id': DEVICE_ID,
            'timestamp': time.time(),
            'description': description
        }
        if audio_b64:
            payload['audio_b64'] = audio_b64
        if self.mqtt.connected:
            self.mqtt.publish_event(payload)
        print('EVENT:', event_type, description)

    def run(self):
        print('GuardYan starting...')
        # Try Wi-Fi + MQTT
        if self.mqtt.connect_wifi():
            print('Wi-Fi connected')
            if self.mqtt.connect_mqtt():
                print('MQTT connected')
        else:
            print('Wi-Fi failed, running offline mode')

        loop_count = 0
        while True:
            loop_count += 1

            # 1. Fall detection
            if self.fall.update():
                self._publish('fall', 'MPU6050检测到疑似跌倒事件')
                self.buzzer.alert_fall()
                self.led.fast_blink()
                time.sleep_ms(500)
                self.led.off()

            # 2. SOS button
            if self.sos.update():
                print('SOS triggered!')
                self.sos_active = True
                self.led.fast_blink()
                self.buzzer.start_sos()
                # Record 3s audio
                audio_b64 = self.audio.record(3)
                self._publish('sos', '长者手动触发SOS按钮', audio_b64)

            # 3. SOS beep loop
            if self.sos_active:
                self.buzzer.tick_sos()

            # 4. Medication reminder (demo: every 60 loops ~30s)
            if loop_count % 60 == 0:
                self.med_active = True
                self.led.breathe()
                self.buzzer.start_med_reminder()

            if self.med_active:
                self.led.tick_breathe()
                self.buzzer.tick_med()

            # 5. MQTT check
            if loop_count % 20 == 0:
                self.mqtt.check_connection()
                self.mqtt.check_messages()

            # 6. LED update
            self.led.update()

            time.sleep_ms(50)

if __name__ == '__main__':
    device = GuardYanDevice()
    device.run()
