# Generated by Trae Work
# GuardYan Firmware - MPU6050 Driver

import machine
import struct
import math
from config import MPU6050_ADDR, PIN_SDA, PIN_SCL, ACCEL_SCALE

class MPU6050:
    def __init__(self):
        self.i2c = machine.I2C(0, sda=machine.Pin(PIN_SDA), scl=machine.Pin(PIN_SCL), freq=400000)
        self._write(0x6B, 0x00)  # wake up
        self._write(0x1C, 0x00)  # accel +-2g
        self._write(0x1B, 0x00)  # gyro +-250deg/s

    def _write(self, reg, val):
        self.i2c.writeto_mem(MPU6050_ADDR, reg, bytes([val]))

    def _read(self, reg, n):
        return self.i2c.readfrom_mem(MPU6050_ADDR, reg, n)

    def read_accel(self):
        data = self._read(0x3B, 6)
        ax, ay, az = struct.unpack('>hhh', data)
        return ax / ACCEL_SCALE, ay / ACCEL_SCALE, az / ACCEL_SCALE

    def read_gyro(self):
        data = self._read(0x43, 6)
        gx, gy, gz = struct.unpack('>hhh', data)
        return gx / 131.0, gy / 131.0, gz / 131.0

    def read_all(self):
        ax, ay, az = self.read_accel()
        gx, gy, gz = self.read_gyro()
        return {
            'ax': ax, 'ay': ay, 'az': az,
            'gx': gx, 'gy': gy, 'gz': gz
        }

    @staticmethod
    def total_accel(ax, ay, az):
        return math.sqrt(ax*ax + ay*ay + az*az)

    @staticmethod
    def pitch_roll(ax, ay, az):
        pitch = math.atan2(ay, math.sqrt(ax*ax + az*az)) * 57.2958
        roll = math.atan2(-ax, math.sqrt(ay*ay + az*az)) * 57.2958
        return pitch, roll
