# Generated by Trae Work
# GuardYan Firmware - MQTT Client Wrapper

import network
import time
from umqtt.simple import MQTTClient
from config import WIFI_SSID, WIFI_PASSWORD, MQTT_BROKER, MQTT_PORT, MQTT_KEEPALIVE, TOPIC_EVENTS, TOPIC_CMD

class MQTTManager:
    def __init__(self, on_message=None):
        self.wlan = network.WLAN(network.STA_IF)
        self.client = None
        self.connected = False
        self.on_message = on_message
        self._retry_count = 0

    def connect_wifi(self, timeout_s=15):
        if self.wlan.isconnected():
            return True
        self.wlan.active(True)
        self.wlan.connect(WIFI_SSID, WIFI_PASSWORD)
        for _ in range(timeout_s * 2):
            if self.wlan.isconnected():
                return True
            time.sleep_ms(500)
        return False

    def connect_mqtt(self):
        try:
            self.client = MQTTClient('guardyan-' + str(time.ticks_ms()), MQTT_BROKER, MQTT_PORT, keepalive=MQTT_KEEPALIVE)
            if self.on_message:
                self.client.set_callback(self.on_message)
            self.client.connect()
            self.client.subscribe(TOPIC_CMD)
            self.connected = True
            self._retry_count = 0
            return True
        except Exception as e:
            print('MQTT connect error:', e)
            self.connected = False
            return False

    def check_connection(self):
        if not self.wlan.isconnected():
            self.connected = False
            return False
        if not self.connected:
            if self._retry_count < 10:
                self._retry_count += 1
                time.sleep_ms(5000)
                return self.connect_mqtt()
        return self.connected

    def publish_event(self, event_dict):
        if not self.connected:
            return False
        try:
            import ujson
            payload = ujson.dumps(event_dict)
            self.client.publish(TOPIC_EVENTS, payload)
            return True
        except Exception as e:
            print('Publish error:', e)
            self.connected = False
            return False

    def check_messages(self):
        if self.connected and self.client:
            try:
                self.client.check_msg()
            except Exception as e:
                print('Check msg error:', e)
                self.connected = False

    def disconnect(self):
        if self.client:
            try:
                self.client.disconnect()
            except:
                pass
        self.connected = False
