# Generated by Trae Work
# GuardYan Firmware - SOS Button Handler

import machine
import time
from config import PIN_SOS

class SOSHandler:
    def __init__(self):
        self.pin = machine.Pin(PIN_SOS, machine.Pin.IN, machine.Pin.PULL_UP)
        self._pressed_at = 0
        self._is_pressed = False
        self.triggered = False
        self.pin.irq(trigger=machine.Pin.IRQ_FALLING, handler=self._on_press)

    def _on_press(self, pin):
        if not self._is_pressed:
            self._is_pressed = True
            self._pressed_at = time.ticks_ms()

    def update(self):
        if self._is_pressed:
            if self.pin.value() == 1:
                # Button released early
                self._is_pressed = False
                self._pressed_at = 0
                return False
            elapsed = time.ticks_diff(time.ticks_ms(), self._pressed_at)
            if elapsed > 2500:  # 2.5 seconds long press
                self._is_pressed = False
                self._pressed_at = 0
                self.triggered = True
                return True
        return False

    def reset(self):
        self.triggered = False
