/** Generated by Trae Work */
/** GuardYan Dashboard - App Bootstrap */

(function() {
  function init() {
    gyStore.init();
    renderNavbar();
    renderToastContainer();
    renderSimulatorPanel();
    highlightCurrentNav();
    initHamburger();
  }

  function renderNavbar() {
    // Navbar is static in HTML, but we can dynamically mark active link
  }

  function initHamburger() {
    const btn = document.getElementById('nav-hamburger');
    const links = document.getElementById('nav-links');
    if (btn && links) {
      btn.addEventListener('click', () => {
        links.classList.toggle('open');
      });
      // Close menu when a link is clicked (mobile UX)
      links.querySelectorAll('a').forEach(a => {
        a.addEventListener('click', () => links.classList.remove('open'));
      });
    }
  }

  function highlightCurrentNav() {
    const path = window.location.pathname;
    const page = path.split('/').pop() || 'index.html';
    document.querySelectorAll('.nav-links a').forEach(a => {
      const href = a.getAttribute('href');
      if (href === page || (page === '' && href === 'index.html')) {
        a.classList.add('active');
      } else {
        a.classList.remove('active');
      }
    });
  }

  function renderToastContainer() {
    if (document.getElementById('toast-container')) return;
    const div = document.createElement('div');
    div.id = 'toast-container';
    div.className = 'toast-container';
    document.body.appendChild(div);
  }

  function renderSimulatorPanel() {
    if (document.getElementById('simulator-panel')) return;
    const panel = document.createElement('div');
    panel.id = 'simulator-panel';
    panel.className = 'simulator-panel';
    panel.innerHTML = `
      <div class="simulator-header" id="simulator-toggle">
        <span>🎮 模拟控制台</span>
        <span id="simulator-chevron">▼</span>
      </div>
      <div class="simulator-body" id="simulator-body">
        <p class="simulator-hint" style="margin-bottom:0.75rem;font-weight:500;">💡 点击下方按钮模拟硬件事件</p>
        <button class="btn btn-danger simulator-btn" data-sim="fall">⚡ 模拟跌倒</button>
        <button class="btn btn-danger simulator-btn" data-sim="sos">🔴 模拟 SOS</button>
        <button class="btn btn-success simulator-btn" data-sim="med">💊 模拟用药提醒</button>
        <button class="btn btn-ghost simulator-btn" data-sim="toggle">📱 切换设备离线</button>
        <div style="border-top:1px solid var(--rule);margin-top:0.75rem;padding-top:0.75rem;">
          <button class="btn btn-ghost simulator-btn" data-sim="reset" style="font-size:0.78rem;color:var(--muted);">🔄 重置演示数据</button>
        </div>
        <p class="simulator-hint">触发后 1~2 秒事件出现在 Dashboard</p>
      </div>
    `;
    document.body.appendChild(panel);

    // Toggle
    document.getElementById('simulator-toggle').addEventListener('click', () => {
      const body = document.getElementById('simulator-body');
      const chevron = document.getElementById('simulator-chevron');
      body.classList.toggle('open');
      chevron.textContent = body.classList.contains('open') ? '▲' : '▼';
      // Remember user preference
      sessionStorage.setItem('gy-sim-open', body.classList.contains('open') ? '1' : '0');
    });

    // Auto-open on first visit
    const simOpened = sessionStorage.getItem('gy-sim-open');
    if (simOpened === null) {
      // First visit — auto open with a short delay for visual impact
      setTimeout(() => {
        const body = document.getElementById('simulator-body');
        const chevron = document.getElementById('simulator-chevron');
        if (body && !body.classList.contains('open')) {
          body.classList.add('open');
          chevron.textContent = '▲';
          sessionStorage.setItem('gy-sim-open', '1');
        }
      }, 800);
    } else if (simOpened === '1') {
      document.getElementById('simulator-body').classList.add('open');
      document.getElementById('simulator-chevron').textContent = '▲';
    }

    // Buttons
    panel.querySelectorAll('[data-sim]').forEach(btn => {
      btn.addEventListener('click', () => handleSimAction(btn.dataset.sim));
    });
  }

  function handleSimAction(action) {
    const elders = gyStore.getElders();

    if (action === 'reset') {
      gyStore.reset();
      window.dispatchEvent(new CustomEvent('gy-data-changed'));
      showToast('演示数据已重置为初始状态', 'success');
      return;
    }

    const onlineElders = elders.filter(e => e.online);

    if (action === 'toggle') {
      const target = onlineElders.length > 0 ? onlineElders[0] : elders[0];
      gyStore.updateElder(target.id, { online: !target.online });
      showToast(`${target.name} 设备已${!target.online ? '离线' : '上线'}`, 'success');
      window.dispatchEvent(new CustomEvent('gy-data-changed'));
      return;
    }

    if (onlineElders.length === 0) {
      showToast('没有在线设备，请先切换设备上线', 'error');
      return;
    }

    const target = onlineElders[Math.floor(Math.random() * onlineElders.length)];
    const delay = 1500 + Math.random() * 1000;

    if (action === 'fall') {
      showToast(`模拟：${target.name} 设备检测到跌倒...`, 'success');
      setTimeout(() => {
        gyStore.addEvent({
          type: 'fall', elderId: target.id,
          description: 'MPU6050检测到疑似跌倒事件'
        });
        window.dispatchEvent(new CustomEvent('gy-data-changed'));
        showToast(`${target.name} 跌倒事件已上报！`, 'error');
      }, delay);
    } else if (action === 'sos') {
      showToast(`模拟：${target.name} 按下 SOS 按钮...`, 'success');
      setTimeout(() => {
        gyStore.addEvent({
          type: 'sos', elderId: target.id,
          description: '长者手动触发SOS按钮'
        });
        window.dispatchEvent(new CustomEvent('gy-data-changed'));
        showToast(`${target.name} SOS 呼救已上报！`, 'error');
      }, delay);
    } else if (action === 'med') {
      const meds = gyStore.getMedications(target.id);
      const medName = meds.length > 0 ? meds[0].drugName : '未指定药品';
      showToast(`模拟：${target.name} ${medName} 用药提醒...`, 'success');
      setTimeout(() => {
        gyStore.addEvent({
          type: 'med', elderId: target.id,
          description: `${medName} 用药时间到，设备已提醒`
        });
        window.dispatchEvent(new CustomEvent('gy-data-changed'));
        showToast(`${target.name} ${medName} 用药提醒已推送`, 'success');
      }, delay);
    }
  }

  window.showToast = function(msg, type) {
    const container = document.getElementById('toast-container');
    if (!container) return;
    const toast = document.createElement('div');
    toast.className = `toast ${type || ''}`;
    toast.textContent = msg;
    container.appendChild(toast);
    setTimeout(() => {
      toast.style.opacity = '0';
      toast.style.transform = 'translateX(100%)';
      toast.style.transition = 'all 0.3s';
      setTimeout(() => toast.remove(), 300);
    }, 3000);
  };

  document.addEventListener('DOMContentLoaded', init);
})();
