/** Generated by Trae Work */
/** GuardYan Dashboard - Data Store */

const STORAGE_KEY = 'guardyan_data_v1';

// ========== Default Data ==========
const DEFAULT_ELDERS = [
  {
    id: 'e1', name: '张奶奶', gender: '女', age: 78,
    address: 'XX社区3栋2单元502', conditions: '高血压、轻度骨质疏松',
    contactName: '王先生（子）', contactPhone: '138****5678',
    deviceId: 'GY-2026-001', battery: 67, online: true,
    firmware: 'v1.2.0', lastReport: Date.now() - 120000
  },
  {
    id: 'e2', name: '李爷爷', gender: '男', age: 82,
    address: 'XX社区5栋1单元301', conditions: '2型糖尿病',
    contactName: '李女士（女）', contactPhone: '139****8910',
    deviceId: 'GY-2026-002', battery: 45, online: true,
    firmware: 'v1.2.0', lastReport: Date.now() - 300000
  },
  {
    id: 'e3', name: '王爷爷', gender: '男', age: 80,
    address: 'XX社区2栋3单元1101', conditions: '冠心病、高血脂',
    contactName: '王强（子）', contactPhone: '137****2233',
    deviceId: 'GY-2026-003', battery: 89, online: true,
    firmware: 'v1.2.0', lastReport: Date.now() - 60000
  }
];

function generateDefaultEvents() {
  const now = new Date();
  const events = [];
  const dayMs = 86400000;

  // SOS events
  events.push({
    id: 'ev-sos-1', type: 'sos', elderId: 'e1',
    timestamp: now.getTime() - 3600000,
    status: 'resolved',
    description: '长者手动触发SOS按钮',
    audioUrl: null
  });
  events.push({
    id: 'ev-sos-2', type: 'sos', elderId: 'e2',
    timestamp: now.getTime() - 86400000 * 2,
    status: 'resolved',
    description: '长者手动触发SOS按钮',
    audioUrl: null
  });

  // Fall event
  events.push({
    id: 'ev-fall-1', type: 'fall', elderId: 'e1',
    timestamp: now.getTime() - 86400000 * 3,
    status: 'resolved',
    description: 'MPU6050检测到疑似跌倒事件',
    audioUrl: null
  });

  // Medication events (past 7 days, 2 drugs x 7 days = 14)
  for (let d = 0; d < 7; d++) {
    const t = new Date(now.getTime() - d * dayMs);
    t.setHours(8, 0, 0, 0);
    events.push({
      id: `ev-med-am-${d}`, type: 'med', elderId: 'e1',
      timestamp: t.getTime(),
      status: d === 0 ? 'pending' : 'resolved',
      description: '降压药用药提醒',
      audioUrl: null
    });
    t.setHours(20, 0, 0, 0);
    events.push({
      id: `ev-med-pm-${d}`, type: 'med', elderId: 'e1',
      timestamp: t.getTime(),
      status: d === 0 ? 'pending' : 'resolved',
      description: '阿司匹林用药提醒',
      audioUrl: null
    });
  }

  // Today's additional pending fall (for demo)
  events.push({
    id: 'ev-fall-today', type: 'fall', elderId: 'e2',
    timestamp: now.getTime() - 18000000,
    status: 'pending',
    description: 'MPU6050检测到疑似跌倒事件',
    audioUrl: null
  });

  return events.sort((a, b) => b.timestamp - a.timestamp);
}

const DEFAULT_MEDICATIONS = [
  {
    id: 'med-1', elderId: 'e1',
    drugName: '氨氯地平片', dosage: '5mg', time: '08:00',
    repeatRule: 'daily', customDays: [],
    records: generateMedRecords('08:00')
  },
  {
    id: 'med-2', elderId: 'e1',
    drugName: '阿司匹林', dosage: '100mg', time: '20:00',
    repeatRule: 'daily', customDays: [],
    records: generateMedRecords('20:00')
  }
];

function generateMedRecords(timeStr) {
  const records = {};
  const now = new Date();
  for (let d = 1; d <= 6; d++) {
    const t = new Date(now.getTime() - d * 86400000);
    const key = formatDateKey(t);
    records[key] = { taken: true, time: timeStr };
  }
  const todayKey = formatDateKey(now);
  records[todayKey] = { taken: false, time: null };
  return records;
}

function formatDateKey(d) {
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

// ========== DataStore Class ==========
class DataStore {
  constructor() {
    this._data = { elders: [], events: [], medications: [] };
    this._listeners = [];
  }

  init() {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      try {
        this._data = JSON.parse(saved);
        // Ensure arrays exist
        if (!this._data.elders) this._data.elders = [];
        if (!this._data.events) this._data.events = [];
        if (!this._data.medications) this._data.medications = [];
      } catch (e) {
        this._resetDefaults();
      }
    } else {
      this._resetDefaults();
    }
    this._persist();
  }

  _resetDefaults() {
    this._data = {
      elders: JSON.parse(JSON.stringify(DEFAULT_ELDERS)),
      events: generateDefaultEvents(),
      medications: JSON.parse(JSON.stringify(DEFAULT_MEDICATIONS))
    };
  }

  _persist() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(this._data));
    this._notify();
  }

  _notify() {
    this._listeners.forEach(cb => cb(this._data));
  }

  subscribe(cb) {
    this._listeners.push(cb);
    return () => {
      this._listeners = this._listeners.filter(fn => fn !== cb);
    };
  }

  // ===== Elders =====
  getElders() { return this._data.elders; }
  getElderById(id) { return this._data.elders.find(e => e.id === id); }

  updateElder(id, patch) {
    const idx = this._data.elders.findIndex(e => e.id === id);
    if (idx >= 0) {
      this._data.elders[idx] = { ...this._data.elders[idx], ...patch };
      this._persist();
    }
  }

  // ===== Events =====
  getEvents(filter = {}) {
    let ev = [...this._data.events].sort((a, b) => b.timestamp - a.timestamp);
    if (filter.elderId) ev = ev.filter(e => e.elderId === filter.elderId);
    if (filter.type) ev = ev.filter(e => e.type === filter.type);
    if (filter.status) ev = ev.filter(e => e.status === filter.status);
    return ev;
  }

  getEventById(id) { return this._data.events.find(e => e.id === id); }

  addEvent(event) {
    const newEvent = {
      id: event.id || ('ev-' + Date.now() + '-' + Math.random().toString(36).substr(2, 5)),
      type: event.type,
      elderId: event.elderId,
      timestamp: event.timestamp || Date.now(),
      status: event.status || 'pending',
      description: event.description || '',
      audioUrl: event.audioUrl || null
    };
    this._data.events.push(newEvent);
    this._persist();
    return newEvent;
  }

  acknowledgeEvent(id, resolution = 'acknowledged') {
    const ev = this._data.events.find(e => e.id === id);
    if (ev) {
      ev.status = resolution;
      this._persist();
    }
  }

  getTodayEventCounts() {
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    const todayEvents = this._data.events.filter(e => e.timestamp >= todayStart.getTime());
    return {
      total: todayEvents.length,
      pending: todayEvents.filter(e => e.status === 'pending').length,
      sos: todayEvents.filter(e => e.type === 'sos').length,
      fall: todayEvents.filter(e => e.type === 'fall').length,
      med: todayEvents.filter(e => e.type === 'med').length
    };
  }

  getRecentEvents(days = 7) {
    const cutoff = Date.now() - days * 86400000;
    return this._data.events
      .filter(e => e.timestamp >= cutoff)
      .sort((a, b) => b.timestamp - a.timestamp);
  }

  // ===== Medications =====
  getMedications(elderId) {
    if (elderId) return this._data.medications.filter(m => m.elderId === elderId);
    return this._data.medications;
  }

  addMedication(med) {
    const newMed = {
      id: med.id || ('med-' + Date.now()),
      elderId: med.elderId,
      drugName: med.drugName,
      dosage: med.dosage,
      time: med.time,
      repeatRule: med.repeatRule || 'daily',
      customDays: med.customDays || [],
      records: {}
    };
    this._data.medications.push(newMed);
    this._persist();
    return newMed;
  }

  updateMedication(id, patch) {
    const idx = this._data.medications.findIndex(m => m.id === id);
    if (idx >= 0) {
      this._data.medications[idx] = { ...this._data.medications[idx], ...patch };
      this._persist();
    }
  }

  deleteMedication(id) {
    this._data.medications = this._data.medications.filter(m => m.id !== id);
    this._persist();
  }

  toggleMedRecord(medId, dateKey, taken) {
    const med = this._data.medications.find(m => m.id === medId);
    if (!med) return;
    if (!med.records) med.records = {};
    if (taken) {
      med.records[dateKey] = { taken: true, time: new Date().toTimeString().slice(0,5) };
    } else {
      delete med.records[dateKey];
    }
    this._persist();
  }

  getTodayMedCount() {
    const todayKey = formatDateKey(new Date());
    return this._data.medications.filter(m => {
      const rec = m.records && m.records[todayKey];
      return rec && rec.taken;
    }).length;
  }

  // ===== Stats =====
  getEventCountsByType(days = 7) {
    const cutoff = Date.now() - days * 86400000;
    const counts = { fall: 0, sos: 0, med: 0 };
    this._data.events.forEach(e => {
      if (e.timestamp >= cutoff) counts[e.type] = (counts[e.type] || 0) + 1;
    });
    return counts;
  }

  getDailyEventCounts(days = 7) {
    const result = [];
    const now = new Date();
    for (let d = days - 1; d >= 0; d--) {
      const date = new Date(now.getTime() - d * 86400000);
      const start = new Date(date); start.setHours(0,0,0,0);
      const end = new Date(date); end.setHours(23,59,59,999);
      const dayEvents = this._data.events.filter(e => e.timestamp >= start.getTime() && e.timestamp <= end.getTime());
      result.push({
        date: `${date.getMonth()+1}/${date.getDate()}`,
        fall: dayEvents.filter(e => e.type === 'fall').length,
        sos: dayEvents.filter(e => e.type === 'sos').length,
        med: dayEvents.filter(e => e.type === 'med').length
      });
    }
    return result;
  }

  // ===== Export / Debug =====
  exportData() { return JSON.parse(JSON.stringify(this._data)); }

  reset() {
    localStorage.removeItem(STORAGE_KEY);
    this._resetDefaults();
    this._persist();
  }
}

// Singleton instance
const store = new DataStore();

// Utility functions
function formatTime(ts) {
  const d = new Date(ts);
  return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
}

function formatDate(ts) {
  const d = new Date(ts);
  const now = new Date();
  const isToday = d.toDateString() === now.toDateString();
  const isYesterday = new Date(now - 86400000).toDateString() === d.toDateString();
  if (isToday) return `今天 ${formatTime(ts)}`;
  if (isYesterday) return `昨天 ${formatTime(ts)}`;
  return `${d.getMonth()+1}月${d.getDate()}日 ${formatTime(ts)}`;
}

function getEventTypeLabel(type) {
  const map = { sos: 'SOS 手动触发', fall: '疑似跌倒', med: '用药提醒' };
  return map[type] || type;
}

function getEventTypeIcon(type) {
  const map = {
    sos: '<svg class="icon" width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="10"/><text x="12" y="16" text-anchor="middle" font-size="11" font-weight="700" fill="#fff">S</text></svg>',
    fall: '<svg class="icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 2v6M8 8l4-6 4 6M6 14l6-4 6 4M8 22l4-8 4 8"/></svg>',
    med: '<svg class="icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M12 8v8M8 12h8"/></svg>'
  };
  return map[type] || '<span style="color:var(--muted);">&#x2022;</span>';
}

// Expose globally (use different name to avoid collision with class DataStore)
window.gyStore = store;
window.GYUtils = { formatTime, formatDate, getEventTypeLabel, getEventTypeIcon, formatDateKey };
