/** Generated by Trae Work */
/** GuardYan Dashboard - Elder Card / Profile Component */

(function() {
  function renderElderList(containerId, onSelect) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const elders = DataStore.getElders();
    container.innerHTML = elders.map(e => `
      <li class="elder-list-item" data-elder="${e.id}">
        <div class="elder-avatar">${e.gender === '女' ? '👵' : '👴'}</div>
        <div>
          <div class="elder-list-name">${e.name} <span class="status-dot ${e.online ? 'online' : 'offline'}"></span></div>
          <div class="elder-list-device">${e.deviceId} · 电量 ${e.battery}%</div>
        </div>
      </li>
    `).join('');

    container.querySelectorAll('[data-elder]').forEach(item => {
      item.addEventListener('click', () => {
        container.querySelectorAll('.elder-list-item').forEach(i => i.classList.remove('active'));
        item.classList.add('active');
        if (onSelect) onSelect(item.dataset.elder);
      });
    });

    // Auto-select first
    const first = container.querySelector('[data-elder]');
    if (first) {
      first.classList.add('active');
      if (onSelect) onSelect(first.dataset.elder);
    }
  }

  function renderElderProfile(containerId, elderId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const elder = DataStore.getElderById(elderId);
    if (!elder) {
      container.innerHTML = '<div class="empty-state">请选择长者</div>';
      return;
    }

    const counts = DataStore.getEventCountsByType(7);
    const daily = DataStore.getDailyEventCounts(7);

    container.innerHTML = `
      <div class="profile-grid">
        <div class="card">
          <div class="card-title">👤 基本信息</div>
          <div class="card-body">
            <div class="info-row"><span class="info-label">姓名</span><span class="info-value">${elder.name}</span></div>
            <div class="info-row"><span class="info-label">年龄 / 性别</span><span class="info-value">${elder.age}岁 / ${elder.gender}</span></div>
            <div class="info-row"><span class="info-label">住址</span><span class="info-value">${elder.address}</span></div>
            <div class="info-row"><span class="info-label">慢病史</span><span class="info-value">${elder.conditions}</span></div>
            <div class="info-row"><span class="info-label">紧急联系人</span><span class="info-value">${elder.contactName}</span></div>
            <div class="info-row"><span class="info-label">联系电话</span><span class="info-value">${elder.contactPhone}</span></div>
          </div>
        </div>
        <div class="card">
          <div class="card-title">📟 设备状态</div>
          <div class="card-body">
            <div class="info-row"><span class="info-label">设备 ID</span><span class="info-value">${elder.deviceId}</span></div>
            <div class="info-row"><span class="info-label">在线状态</span><span class="info-value"><span class="status-dot ${elder.online ? 'online' : 'offline'}"></span> ${elder.online ? '在线' : '离线'}</span></div>
            <div class="info-row"><span class="info-label">电量</span><span class="info-value">${elder.battery}%</span></div>
            <div class="battery-bar"><div class="battery-fill ${elder.battery > 50 ? 'high' : elder.battery > 20 ? 'medium' : 'low'}" style="width:${elder.battery}%"></div></div>
            <div class="info-row"><span class="info-label">固件版本</span><span class="info-value">${elder.firmware}</span></div>
            <div class="info-row"><span class="info-label">最后上报</span><span class="info-value">${GYUtils.formatDate(elder.lastReport)}</span></div>
            <div style="margin-top:0.75rem;display:flex;gap:0.5rem;">
              <button class="btn btn-ghost btn-sm" id="btn-reboot">🔄 远程重启</button>
              <button class="btn btn-ghost btn-sm" id="btn-mute">🔇 远程静音</button>
            </div>
          </div>
        </div>
      </div>
      <div class="card" style="margin-top:1rem;">
        <div class="card-title">📊 近7天事件统计</div>
        <div style="display:flex;gap:1rem;margin-bottom:0.75rem;">
          <div style="text-align:center;flex:1;"><div style="font-size:1.5rem;font-weight:700;color:var(--accent2);">${counts.fall}</div><div style="font-size:0.8rem;color:var(--muted);">跌倒</div></div>
          <div style="text-align:center;flex:1;"><div style="font-size:1.5rem;font-weight:700;color:var(--accent);">${counts.sos}</div><div style="font-size:0.8rem;color:var(--muted);">SOS</div></div>
          <div style="text-align:center;flex:1;"><div style="font-size:1.5rem;font-weight:700;color:var(--muted);">${counts.med}</div><div style="font-size:0.8rem;color:var(--muted);">用药</div></div>
        </div>
        <canvas id="chart-events" height="180"></canvas>
      </div>
    `;

    // Bind remote buttons
    document.getElementById('btn-reboot')?.addEventListener('click', () => {
      showToast(`已向 ${elder.deviceId} 发送重启指令`, 'success');
    });
    document.getElementById('btn-mute')?.addEventListener('click', () => {
      showToast(`已向 ${elder.deviceId} 发送静音指令`, 'success');
    });

    // Render chart
    renderChart(daily);
  }

  function renderChart(dailyData) {
    const ctx = document.getElementById('chart-events');
    if (!ctx || typeof Chart === 'undefined') return;

    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: dailyData.map(d => d.date),
        datasets: [
          { label: '跌倒', data: dailyData.map(d => d.fall), backgroundColor: '#E67E22' },
          { label: 'SOS', data: dailyData.map(d => d.sos), backgroundColor: '#C0392B' },
          { label: '用药', data: dailyData.map(d => d.med), backgroundColor: '#8B7355' }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'top' } },
        scales: { y: { beginAtZero: true, ticks: { stepSize: 1 } } }
      }
    });
  }

  window.ElderCard = { renderList: renderElderList, renderProfile: renderElderProfile };
})();
